### ISSUE TITLE
Create a runbook session

### ISSUE THREAD

**Issue by olblak** [updatecli/website#1080]
## Summary

It would be nice to have a runbook section where we document more unusual manifest but yet useful

### Basic example

Retrieve the latest lts nodejs version

```
sources:
  nodeLatestLTSVersionFromJson:
    name: Get value from json
    kind: json
    spec:
      file: https://nodejs.org/dist/index.json
      key: .(lts!=false).version
```
### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?
